from wq_clt_input import *
input_labels = {
            "top_flange_width": str(TOP_FLANGE[0]),
            "top_flange_thickness": str(TOP_FLANGE[1]),
            "bottom_flange_width": str(BOTTOM_FLANGE[0]),
            "bottom_flange_thickness": str(BOTTOM_FLANGE[1]),
            "wall_height": str(WALL[0]),
            "wall_thickness": str(WALL[1]),
            "steel_modulus": str(STEEL_YOUNG),
            "steel_density": str(STEEL_DENSITY),
            "clt_layers": str(LAYERS),
            "clt_orientation": str(ORIENTATION),
            "clt_modulus_0": str(CLT_YOUNG[0]),
            "clt_modulus_90": str(CLT_YOUNG[1]),
            "rolling_modulus": str(ROLLING_MODULUS),
            "clt_density": str(CLT_DENSITY),
            "connector_0": str(KS[0]),
            "connector_90": str(KS[1]),
            "period": str(PERIOD),
            "screw_amount": str(SCREW_AMOUNT),
            "span_beam": str(SPANS[0]),
            "span_ clt": str(SPANS[1]),
            "gap": str(GAP),
            "clt_amount": str(SLAB_AMOUNT),
            "s_factor": str(S),
            "wq_load": str(Q),
            "human": str(HUMAN),
            "gravity": str(GRAVITY),
        }

